"""add source_url to documents

Revision ID: 41dc3adac4e1
Revises: caa96d4cd54d
Create Date: 2026-08-14 22:48:05.263460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dc3adac4e1'
down_revision: Union[str, Sequence[str], None] = 'caa96d4cd54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
